language: go
sudo: required

services:
  - docker

matrix:
  include:
  - go: tip
    os: linux
    env: TARGET=linux
  - go: tip
    os: linux
    env: TARGET=windows
  - go: tip
    os: linux
    env: TARGET=docker
  - go: tip
    os: osx
    env: TARGET=osx

before_install:
- if [ "$TARGET" = "windows" ]; then sudo apt update; fi

install:
- if [ "$TARGET" = "windows" ]; then sudo apt install gcc-mingw-w64 libc6-dev-i386; fi

script:
- ./ci/travis-build.sh

after_success:
- ./ci/travis-after-success.sh

deploy:
  - provider: s3
    on:
      repo: CrunchyData/pg_tileserv
      branch: master
      condition: $TARGET != docker
    region: us-east-1
    bucket: postgisftw
    local_dir: "./upload"
    overwrite: true
    verbose: true
    edge: true
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    cleanup: false
  - provider: s3
    on:
      repo: CrunchyData/pg_tileserv
      tags: true
      condition: $TARGET != docker
    region: us-east-1
    bucket: postgisftw
    local_dir: "./upload"
    overwrite: true
    verbose: true
    edge: true
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    cleanup: false
