language: go
sudo: false

matrix:
  include:
  - go: tip
    os: linux
    env: CROSS_COMPILE=true
  - go: tip
    os: osx
    env: CROSS_COMPILE=false

before_install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt update; fi

install:
- if [ "$CROSS_COMPILE" = "true" ]; then sudo apt install gcc-mingw-w64 libc6-dev-i386; fi

script:
- mkdir upload
- go build
- zip -r upload/pg_tileserv_snapshot_${TRAVIS_OS_NAME}.zip pg_tileserv README.md LICENSE.md assets/
- if [ "$TRAVIS_OS_NAME" = "linux" -a "$CROSS_COMPILE" = "true" ]; then env CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc go build -v; zip -r upload/pg_tileserv_snapshot_windows.zip pg_tileserv.exe README.md assets/ LICENSE.md; fi

deploy:
    provider: s3
    on:
        repo: CrunchyData/pg_tileserv
        branch: master
    region: us-east-1
    bucket: postgisftw
    local_dir: "./upload"
    overwrite: true
    verbose: true
    edge: true
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    cleanup: false
